spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb:http://customer-service
          predicates:
            - Path=/api/v1/customers/**
        - id: order-service
          uri: lb:http://order-service
          predicates:
            - Path=/api/v1/orders/**
        - id: order-lines-service
          uri: lb:http://order-service
          predicates:
            - Path=/api/v1/orders-lines/**
        - id: product-service
          uri: lb:http://product-service
          predicates:
            - Path=/api/v1/products/**

server:
  port: 8222
