spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb:http://customer-service
          predicates:
            - Path=/api/v1/customers/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
        - id: order-lines-service
          uri: lb://order-lines-service
          predicates:
            - Path=/api/v1/orders-lines/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
      globalcors:
        cors-configurations:
          '[/**]': # Applies to all paths
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: false
            maxAge: 3600


server:
  port: 8222
