eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka

spring:
  cloud:
    config:
      override-system-properties: false

application:
  config:
    api-gateway:
      url: http://localhost:8222
    local:
      url: http://localhost:${server.port}

management:
  tracing:
    sampling:
      probability: 1.0